In [1]:
import pandas as pd
import numpy as np
import io
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files
uploaded = files.upload()

Saving diabetes.csv to diabetes.csv

In [3]:
diabetes_df = pd.read_csv(io.BytesIO(uploaded["diabetes.csv"]))
display(diabetes_df)

     Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [7]:
data = diabetes_df.drop(['Outcome'], axis = 1)

In [8]:
# Replacing 0 with nan values
data.replace(0, np.nan, inplace = True)

In [9]:
data.isnull().sum().sort_values(ascending = False)

Insulin                     374
SkinThickness               227
Pregnancies                 111
BloodPressure                35
BMI                          11
Glucose                       5
Age                           0
DiabetesPedigreeFunction      0
dtype: int64

In [10]:
# Handling missing data
data ['Insulin'].unique()

array([ nan,  94., 168.,  88., 543., 846., 175., 230.,  83.,  96., 235.,
       146., 115., 140., 110., 245.,  54., 192., 207.,  70., 240.,  82.,
        36.,  23., 300., 342., 304., 142., 128.,  38., 100.,  90., 270.,
        71., 125., 176.,  48.,  64., 228.,  76., 220.,  40., 152.,  18.,
       135., 495.,  37.,  51.,  99., 145., 225.,  49.,  50.,  92., 325.,
        63., 284., 119., 204., 155., 485.,  53., 114., 105., 285., 156.,
        78., 130.,  55.,  58., 160., 210., 318.,  44., 190., 280.,  87.,
       271., 129., 120., 478.,  56.,  32., 744., 370.,  45., 194., 680.,
       402., 258., 375., 150.,  67.,  57., 116., 278., 122., 545.,  75.,
        74., 182., 360., 215., 184.,  42., 132., 148., 180., 205.,  85.,
       231.,  29.,  68.,  52., 255., 171.,  73., 108.,  43., 167., 249.,
       293.,  66., 465.,  89., 158.,  84.,  72.,  59.,  81., 196., 415.,
       275., 165., 579., 310.,  61., 474., 170., 277.,  60.,  14.,  95.,
       237., 191., 328., 250., 480., 265., 193.,  79.,  86., 326., 188.,
       106.,  65., 166., 274.,  77., 126., 330., 600., 185.,  25.,  41.,
       272., 321., 144.,  15., 183.,  91.,  46., 440., 159., 540., 200.,
       335., 387.,  22., 291., 392., 178., 127., 510.,  16., 112.])

In [11]:
np.round(data['Insulin'].mean())

156.0

In [12]:
data ['Insulin'].replace(np.nan, np.round(data['Insulin'].mean()), inplace = True)

In [16]:
from sklearn.impute import SimpleImputer
# strategy = 'median', 'mean'
impute = SimpleImputer(strategy = 'median')
data_array = impute.fit_transform(data)

In [17]:
data_array

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [18]:
diabetes_df1 = pd.DataFrame(data_array, columns= data.columns)
diabetes_df1

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction   Age
0            6.0    148.0           72.0  ...  33.6                     0.627  50.0
1            1.0     85.0           66.0  ...  26.6                     0.351  31.0
2            8.0    183.0           64.0  ...  23.3                     0.672  32.0
3            1.0     89.0           66.0  ...  28.1                     0.167  21.0
4            4.0    137.0           40.0  ...  43.1                     2.288  33.0
..           ...      ...            ...  ...   ...                       ...   ...
763         10.0    101.0           76.0  ...  32.9                     0.171  63.0
764          2.0    122.0           70.0  ...  36.8                     0.340  27.0
765          5.0    121.0           72.0  ...  26.2                     0.245  30.0
766          1.0    126.0           60.0  ...  30.1                     0.349  47.0
767          1.0     93.0           70.0  ...  30.4                     0.315  23.0

[768 rows x 8 columns]